import BaseTool from "@/tools/base";
import { ToolNames } from "@/tools/constants";
import { z } from "zod";
import { listFixItems } from "@/utils/site-audit-api";
import { formatFixItems, formatError, toResult } from "@/utils/format";
import { CallToolResult } from "@modelcontextprotocol/sdk/types.js";

class ListFixItemsTool extends BaseTool {
    private accessToken: string;
    constructor(accessToken = "") { super(); this.accessToken = accessToken; }

    name = ToolNames.LIST_FIX_ITEMS;
    description =
        "Read the fix list saved against an audit — the proposed metadata changes and notes a user " +
        "has recorded for each page, ready to hand to a developer.\n\n" +
        "These are hand-authored and are not regenerated by re-running an audit. Returns each " +
        "item's ID for use with **deleteFixItem**.";

    annotations = {
        title: "List Fix Items",
        readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true,
    };

    inputSchema = z.object({ auditId: z.string().describe("Audit ID.") });
    outputSchema = z.object({ auditId: z.string(), fixItems: z.array(z.any()) });

    async execute(args: z.infer<typeof this.inputSchema>): Promise<CallToolResult> {
        if (!this.accessToken) return toResult(formatError("List Fix Items", "Site Audit requires OAuth authentication. Reconnect the OpenGraph MCP server to authorize."));
        try {
            return toResult(formatFixItems(args.auditId, await listFixItems(args.auditId, this.accessToken)));
        } catch (error: unknown) {
            return toResult(formatError("List Fix Items", error instanceof Error ? error.message : String(error)));
        }
    }
}
export default ListFixItemsTool;
