import BaseTool from "@/tools/base";
import { ToolNames } from "@/tools/constants";
import { z } from "zod";
import { deleteFixItem } from "@/utils/site-audit-api";
import { formatFixItemDeleted, formatError, toResult } from "@/utils/format";
import { CallToolResult } from "@modelcontextprotocol/sdk/types.js";

class DeleteFixItemTool extends BaseTool {
    private accessToken: string;
    constructor(accessToken = "") { super(); this.accessToken = accessToken; }

    name = ToolNames.DELETE_FIX_ITEM;
    description =
        "Permanently remove one entry from an audit's fix list.\n\n" +
        "Fix items are hand-authored and cannot be regenerated by re-running the audit, so confirm " +
        "with the user first. Item IDs come from **listFixItems**.";

    annotations = {
        title: "Delete Fix Item",
        readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true,
    };

    inputSchema = z.object({
        auditId: z.string().describe("Audit ID."),
        fixItemId: z.string().describe("Fix item ID from listFixItems."),
    });
    outputSchema = z.object({ auditId: z.string(), fixItemId: z.string(), deleted: z.boolean() });

    async execute(args: z.infer<typeof this.inputSchema>): Promise<CallToolResult> {
        if (!this.accessToken) return toResult(formatError("Delete Fix Item", "Site Audit requires OAuth authentication. Reconnect the OpenGraph MCP server to authorize."));
        try {
            await deleteFixItem(args.auditId, args.fixItemId, this.accessToken);
            return toResult(formatFixItemDeleted(args.auditId, args.fixItemId));
        } catch (error: unknown) {
            return toResult(formatError("Delete Fix Item", error instanceof Error ? error.message : String(error)));
        }
    }
}
export default DeleteFixItemTool;
